homeassistant:
  # Customization file
  customize: !include customize.yaml

# Enables the frontend
frontend:
  themes:
    regular:
      primary-color: "#4b93ad"
      
      # Cards
      ha-card-border-radius: "10px"
      ha-card-box-shadow: "0px 5px 5px rgba(0,0,0,0.3)"
      
    dark:
      # Accent Colour (Edit this to change the accent) #
      accent: "#40ccff"
    
    
      # Background
      primary-background-color: "#121212"
    
      # Text
      primary-text-color: "#FFFFDE"
      secondary-text-color: "#d2dad8"
      disabled-text-color: "#b81c1c"
      sidebar-selected-text-color: "var(--accent)"
    
      # Card
      card-background-color: "#1D1D1D"
      paper-card-background-color: "#1D1D1D"
      
      # Cards
      ha-card-border-radius: "10px"
      ha-card-box-shadow: "0px 5px 5px rgba(0,0,0,0.3)"
    
      # Colours
      primary-color: "#737373"
      secondary-background-color: "#1D1D1D"
      accent-color: "var(--accent)"
      dark-primary-color: "var(--accent)"
      light-primary-color: "var(--accent)"
    
      # Controls
      toggle-button-color: "var(--accent)"
      paper-toggle-button-checked-button-color: "var(--accent)"
      paper-toggle-button-checked-bar-color: "var(--accent)"
      paper-toggle-button-checked-ink-color: "var(--accent)"
      paper-toggle-button-unchecked-button-color: "#A5A5A5"
      paper-toggle-button-unchecked-bar-color: "#787878"
      paper-checkbox-checked-color: "var(--accent)"
      paper-checkbox-checked-ink-color: "var(--accent)"
      paper-radio-button-checked-color: "var(--accent)"
      paper-input-container-focus-color: "var(--accent)"
      paper-dropdown-menu-focus-color: "var(--accent)"
      slider-color: "var(--accent)"
      mdc-theme-primary: "var(--accent)"
    
      # Icons
      state-icon-color: "#A0A0A0"
      state-icon-active-color: "var(--accent)"
      sidebar-selected-icon-color: "var(--accent)"
      sidebar-icon-color: "#A0A0A0"
    
      # Badges
      ha-label-badge-color: "var(--accent)"
      label-badge-background-color: "#121212"
      label-badge-text-color: "var(--secondary-text-color)"
    
      # Tabs
      paper-tab-ink: "var(--accent)"
    
      # Divider
      divider-color: "#2D2D2D"
    
      # Lumo
      lumo-base-color: "#2D2D2D"
      lumo-tint-5pct: "none"
      lumo-shade-5pct: "#272727"
      paper-grey-200: "#272727"
      lumo-primary-color-10pct: "#2D2D2D"
      lumo-primary-color-50pct: "none"
      lumo-box-shadow-m: "none"
      lumo-primary-color: "var(--accent)"
      lumo-header-text-color: "var(--primary-text-color)"
      lumo-body-text-color: "var(--primary-text-color)"
      lumo-tertiary-text-color: "var(--secondary-text-color)"
      lumo-primary-contrast-color: "var(--primary-text-color)"

# Enables configuration UI
config:

# browser_mod:
      
recorder:
  purge_keep_days: 7
  purge_interval: 1
  exclude:
    domains:
      - automation
      - weblink
      - updater
      - zwave
      - zone
      - group
      - camera

updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

#device_tracker:
device_tracker:
  - platform: google_maps
    username: !secret gm_u
  - platform: bluetooth_tracker
#  - platform: nmap_tracker
 #   hosts: 192.168.0.1/24

system_health:

hassio:

weather:
  - platform: darksky
    api_key: !secret ds_a
    mode: daily
    
google:
  client_id: !secret gc_i
  client_secret: !secret gc_s
    
tuya:
  username: !secret tu_u
  password: !secret tu_p
  country_code: 1
    
# Enables a map showing the location of tracked devices
map:

zone:
  - name: Work
    latitude: 
    longitude: 
    radius: 400
    icon: mdi:school
    
  - name: RiverPark
    latitude: 36.847744
    longitude: -119.791128
    radius: 400
    icon: mdi:store
    
  - name: VA
    latitude: 36.773336
    longitude: -119.779766  
    radius: 400
    icon: mdi:hospital-building

  - name: School A
    latitude:  
    longitude:  
    radius: 200
    icon: mdi:school

  - name: School Y
    latitude:  
    longitude:  
    radius: 200
    icon: mdi:school

  - name: School F
    latitude:  
    longitude:  
    radius: 600
    icon: mdi:school

# This will override the default home zone
  - name: Home
    latitude:  
    longitude:  
    radius: 150
    icon: mdi:home
      
proximity:
  home_xiphone:
    devices:
      - device_tracker.google_maps_ 
    tolerance: 50
    unit_of_measurement: ft
  home_pingkham:
    devices:
      - device_tracker.google_maps_ 
    tolerance: 50
    unit_of_measurement: ft    
  home_james:
    devices:
      - device_tracker.google_maps_ 
    tolerance: 50
    unit_of_measurement: ft 

# Track the sun
sun:

#ecovacs:
#  username: !secret ev_u
#  password: !secret ev_p
#  country: us
#  continent: na

shopping_list:

tesla:
  username: !secret te_u
  password: !secret te_p

switch:
  - platform: switchmate
    mac: ' '
  - platform: switchmate
    mac: ' '
    name: Kitchen Lights
    flip_on_off: true
  - platform: switchmate
    mac: ' '
    name: Dining Room

light:
  - platform: flux_led
    devices:
      192.168.0.130:
        name: bar lights
     
mobile_app:

input_text:
  tts_anouncement:
    name: Anouncement
    initial: Hello
  pool_timer_manual:
    name: Pump Time Remaining
    initial: 0
  elec_rate:
    name: Electric Billing Use
    initial: Off Peak
  peaktoday:
    name: 'Peak KWh Today'
    initial: 0
  speaktoday:
    name: 'Peak KWh Start'
    initial: 0 
  epeaktoday:
    name: 'Peak KWh End'
    initial: 0
  ch_start:
    name: 'Charge Start'
    initial: 0   
  ch_end:
    name: 'Charge end'
    initial: 0 
  ch_total:
    name: 'Charge amount'
    initial: 0 
    
input_number:
  povertime:
    name: Override Time
    initial: 1
    min: 1
    max: 24
    step: 1
  pittemp:
    name: Pit Temperature
    initial: 250
    min: 200
    max: 500
    step: 25
    unit_of_measurement: "F"
  pid_factor:
    name: PID Factor
    initial: .5
    min: .1
    max: 1
    step: .1
          
notify:
  - platform: pushbullet
    name: pushbullet
    api_key: !secret pb_a
  - platform: lannouncer
    name: nexus
    host:  
  - platform: lannouncer
    name: blu
    host:  

alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code: !secret a_c
    pending_time: 10
    delay_time: 20
    trigger_time: 1000
    disarmed:
      trigger_time: 0
    armed_home:
      pending_time: 0
      delay_time: 0

tts:
  - platform: google_translate

person:

cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
camera: !include cameras.yaml
binary_sensor: !include binary_sensors.yaml
input_select: !include input_selects.yaml        
input_boolean: !include input_booleans.yaml
