esphome:
  name: lr1
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: ''
  password: ''
  manual_ip:
    static_ip: 192.168.0.74
    gateway: 192.168.0.1
    subnet: 255.255.255.0
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Light 1 Fallback Hotspot"
    password: "esphomeio"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

sensor:
  - platform: wifi_signal
    name: "LR1 WiFi Signal Sensor"
    update_interval: 60s
    
output:
  - platform: esp8266_pwm
    id: output_red
    pin: GPIO04
  - platform: esp8266_pwm
    id: output_green
    pin: GPIO12
  - platform: esp8266_pwm
    id: output_blue
    pin: GPIO14
  - platform: esp8266_pwm
    id: output_cwhite
    pin: GPIO05
  - platform: esp8266_pwm
    id: output_wwhite
    pin: GPIO13

light:
  - platform: rgbww
    name: "LR1"
    red: output_red
    green: output_green
    blue: output_blue
    cold_white: output_cwhite
    warm_white: output_wwhite
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K
    effects:
      # Use default parameters:
      - random:
      - strobe:
      - flicker:

    # Ensure the light turns on by default if the physical switch is actuated.
    restore_mode: ALWAYS_ON
