esphome:
  name: garage
  platform: ESP8266
  board: d1_mini_lite

wifi:
  networks:
  - ssid: 	
    password: 	
  - ssid: 	
    password: 	
  manual_ip:
    static_ip: 192.168.0.50
    gateway: 192.168.0.1
    subnet: 255.255.255.0
  power_save_mode: none

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "garage Fallback Hotspot"
    password: "IQnvgR3mxjH4"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

    
sensor:
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s
    
    
switch:
  - platform: gpio
    name: "lg_garage_switch"
    pin: D1
    inverted: no
    id: large_gr_switch
  - platform: template
    name: "Large Remote"
    turn_on_action:
    - switch.turn_on: large_gr_switch
    - delay: 1500ms
    - switch.turn_off: large_gr_switch
  - platform: gpio
    name: "sm_garage_switch"
    pin: D2
    id: small_gr_switch
    inverted: no
  - platform: template
    name: "Small Remote"
    turn_on_action:
    - switch.turn_on: small_gr_switch
    - delay: 500ms
    - switch.turn_off: small_gr_switch
